
development:
  adapter: postgresql
  encoding: unicode
  database: storylines_development
  pool: 5
  username: cristi
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: storylines_test
  pool: 5
  username: cristi
  password: 
